server:
  port: 9000
  servlet:
    context-path:

spring:
  application:
    name: gateway-service
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/loja-cloud
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false


zuul:
  sensitive-headers: Set-Cookie
  host:
    connect-timeout-millis: 10000
    connection-request-timeout-millis: 10000
    socket-timeout-millis: 1000000
    max-total-connections: 1000
    max-per-route-connections: 50

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 1000

jwt:
  config:
    login-url: /auth/login
    type: signed

auth:
  ribbon:
    listOfServers: http://localhost:8083

servico-pessoa:
  ribbon:
    listOfServers: http://localhost:9080

servico-produto:
  ribbon:
    listOfServers: http://localhost:9002





