server:
  port: 9093
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loja-cloud
    username: postgres
    password: password
    pool:
      enabled: true
      initial-size: 10

  main:
    banner-mode: off
