server:
  port: 9080
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  application:
    name: servico-pessoa
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/loja-cloud
    username: postgres
    password: postgres
    pool:
      enabled: true
    application:
      name: servico-pessoa
    boot:
      admin:
        client:
          url: http://localhost:1111
          username: admin
          password: 123
    main:
      banner-mode: off

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

jwt:
  config:
    type: signed

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,info"
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "metrics"
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

info:
  application:
    nome: "Serviço dos Usuários"
    descricao: "API de Usuários"