server:
  port: 9091
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loja-cloud
    username: postgres
    password: password
    pool:
      enabled: true
  application:
    name: servico-pessoa
  boot:
    admin:
      client:
        url: http://localhost:1111
        username: admin
        password: 123
  main:
    banner-mode: off

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      servico:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,info"
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "metrics"
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

info:
  application:
    nome: "Serviço dos Pessoas"
    descricao: "API de Pessoas"

eureka:
  instance:
    hostname: localhost