server:
  port: 9002
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
        username: admin
        password: 123
        instance:
          prefer-ip: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/loja-cloud
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.generate_statistics]": true
    defer-datasource-initialization: true
    show-sql: true
  main:
    banner-mode: off
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,info"
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "metrics"
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

info:
  application:
    nome: "Serviço dos Produtos"
    descricao: "API de Produtos"
