server:
  port: 9002
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecomerce
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  main:
    banner-mode: off
  sql:
    init:
      mode: always